# -*- coding: utf-8 -*-
"""qa_squad_model_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhnOUFwhfcfbp4HKOkZTqGKjmrcnLB73
"""

# aaron e
# ae-314
# question and answering demo with examples

!pip install -U transformers

"""## Local Inference on GPU
Model page: https://huggingface.co/ae-314/question_answering_model

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/ae-314/question_answering_model)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("question-answering", model="ae-314/question_answering_model")

question = "Why can't parasitic plants use photosynthesis?"
context = "Plants largely make their energy using photosynthesis, except for parasitic plants which have lost the genes for chlorophyll and so can't use photosynthesis and so must use other plants or fungi for energy."

pipe(question = question, context=context)